# simple_llm.py question answer

# --------------------------------------------------
# IMPORTS
# --------------------------------------------------

# LangGraph components for creating the workflow
from langgraph.graph import StateGraph, START, END

# OpenAI chat model from LangChain
from langchain_google_genai import ChatGoogleGenerativeAI

# Used to define the structure of our state
from typing import TypedDict

# Used to load variables from the .env file
from dotenv import load_dotenv


# --------------------------------------------------
# 1. LOAD ENVIRONMENT VARIABLES
# --------------------------------------------------

# Loads OPENAI_API_KEY from the .env file
load_dotenv()


# --------------------------------------------------
# 2. CREATE THE LLM
# --------------------------------------------------

# Create the OpenAI chat model
model = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash"
)


# --------------------------------------------------
# 3. DEFINE STATE
# --------------------------------------------------

class LLMState(TypedDict):
    """
    State contains the data that flows through our graph.
    """

    question: str     # Question given by the user
    answer: str       # Answer generated by the LLM


# --------------------------------------------------
# 4. CREATE THE GRAPH
# --------------------------------------------------

# Create a StateGraph using our LLMState
graph = StateGraph(LLMState)


# --------------------------------------------------
# 5. DEFINE NODE
# --------------------------------------------------

def llm_qa(state: LLMState) -> LLMState:
    """
    Takes a question from the state,
    sends it to the LLM,
    and stores the answer in the state.
    """

    # Extract the question from the state
    question = state["question"]

    # Create a prompt for the LLM
    prompt = f"Answer the following question: {question}"

    # Send the prompt to the LLM
    # .content gives us only the text of the response
    answer = model.invoke(prompt).content

    # Store the LLM's answer in the state
    state["answer"] = answer

    return state


# --------------------------------------------------
# 6. ADD NODE
# --------------------------------------------------

# Add the llm_qa function as a node
graph.add_node("llm_qa", llm_qa)


# --------------------------------------------------
# 7. ADD EDGES
# --------------------------------------------------

# Define the execution flow:
#
# START → llm_qa → END

graph.add_edge(START, "llm_qa")

graph.add_edge("llm_qa", END)


# --------------------------------------------------
# 8. COMPILE THE GRAPH
# --------------------------------------------------

# Compile the graph into an executable workflow
workflow = graph.compile()


# --------------------------------------------------
# 9. PROVIDE INITIAL INPUT
# --------------------------------------------------

# Initial state contains only the question
initial_state = {
    "question": "How far is the Moon from the Earth?"
}


# --------------------------------------------------
# 10. EXECUTE THE GRAPH
# --------------------------------------------------

# Pass the initial state into the workflow
final_state = workflow.invoke(initial_state)


# --------------------------------------------------
# 11. PRINT THE ANSWER
# --------------------------------------------------

# Get the answer generated by the LLM
print(final_state["answer"])